### ISSUE TITLE
Exemple with script Turn on

### ISSUE THREAD

**Issue by nelsonamen** [Nerwyn/service-call-tile-feature#1]
Hi
Can you make exemple with a script Turn on

**Comment by nelsonamen** [comment]
type: custom:service-call
buttons:
  - service: script.iniciar_aspirador
    icon: mdi:play
  - service: script.limpar_o_aspirador
    icon: mdi:broom

**Comment by Nerwyn** [comment]
Bro I started writing this yesterday as an experiment and only just now shared it on the Home Assistant website 😆. v1.0.0 released and README updated with examples.
