### ISSUE TITLE
Card not updating on state changes

### ISSUE THREAD

**Issue by pkamp** [Nerwyn/service-call-tile-feature#17]
I used buttons to turn my lights on and off and used a template to set the buttons's color to the light's current rgb_color (as shown in the examples)

e.g.:
```
style:
    '--color': |
        {% if is_state("light.sunroom_ceiling", "on") %}
            rgb({{ state_attr("light.sunroom_ceiling", "rgb_color") }})
        {% else %}
            initial
        {% endif %}
```

I expected to see the color change when turning the light on or off, however the card does not update at all. It would be nice to have a visual feedback by triggering a card update on state changes

**Comment by Nerwyn** [comment]
It's working for me. You also didn't use the feature or bug templates and this issue is missing actionable information. Which version are you using? What is your config? Are you sure the light entity attribute information is updating when you change it? What browser and device are you using?

**Comment by pkamp** [comment]
I further investigated my problem and it turned out, that the parent card i used was causing this problem.

Everything works fine now, thanks for this awesome card
