### ISSUE TITLE
Selector doesnt respond to color settings

### ISSUE THREAD

**Issue by magune** [Nerwyn/service-call-tile-feature#35]
Hi,

I tried the new Beta today, as a first time user of the service call tile plugin.

I tried to make a selector button group, but unfortunaltely after selecting a button the white icon is on a white button background so the icon is no longer visible.  Any attempt to change icon or button color make no effect whatsoever.

Here is my YAML:

              - type: tile
                entity: input_select.sceneval_hela_lagenheten
                icon: mdi:home
                name: Hela lägenheten
                features:
                  - type: custom:service-call
                    entries:
                      - type: selector
                        style:
                          '--color': rgb(124,56,74)   
                          height: 100px
                        options:
                          - icon: mdi:lightbulb-on-10                 
                            option: Mysbelysning
                            style:
                              '--color': rgb(124,56,74)  
                            icon_style:
                              color: rgb(37, 79, 55)  
                            tap_action:
                              action: call-service
                              service: script.hela_lagenheten_mysbelysning
                          - icon: mdi:lightbulb-on-10
                            option: Normalbelysning
                            tap_action:
                              action: call-service
                              service: script.hela_lagenheten_normalbelysning
                          - icon: mdi:lightbulb-on
                            option: Maxbelysning
                            tap_action:
                              action: call-service
                              service: script.hela_lagenheten_stadbelysning
                          - icon: mdi:lightbulb-off
                            option: Släckt
                            tap_action:
                              action: call-service
                              service: script.hela_lagenheten_slackt

Before I click any button, it looks nice:

<img width="282" alt="image" src="https://github.com/user-attachments/assets/8c9c689a-9173-4f8f-9724-a758eeabba81">

But after clicking, i no longer see the icon of the clicked button:

<img width="286" alt="image" src="https://github.com/user-attachments/assets/c1d23166-2bd1-48da-a9a2-1bf429a7482f">

Is this a bug or do i do something wrong?

**Comment by Nerwyn** [comment]
As you've found out, styles have been reworked to use the HTML `style` tag and accept a CSS string instead of YAML. You can set icon color either using `--icon-color` in host or .icon, or `color` in icon.

The white background and icon is a result of your tile card color being white. You have to either change that or the icon color, as you've done.
