### ISSUE TITLE
Selector button icon size

### ISSUE THREAD

**Issue by magune** [Nerwyn/service-call-tile-feature#36]
Is there any possibility to get the selector buttons a bit larger? in this screenshot the above part is my old solution, and in the bottom half the servicecalltile solution, with "too small" icons:

<img width="299" alt="image" src="https://github.com/user-attachments/assets/3e43c4ae-ac73-4dfb-b981-64eba69fbb87">

(too small in this context means they are to small to click on with a finger on a wall mounted ipad)

**Comment by Nerwyn** [comment]
The icon sizes were reduced to match the Home Assistant built in selectors, they were actually too big before. Set `--mdc-icon-size` on each selector button.

```css
:host {
  --mdc-icon-size: 32px !important;
}
```

I can see if I can rework this style so it can also be set at the entire selector level.

**Comment by magune** [comment]
That worked, thank you!!

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Nerwyn ***@***.***>
Skickat: Wednesday, July 17, 2024 6:23:41 PM
Till: Nerwyn/service-call-tile-feature ***@***.***>
Kopia: Magnus Unemyr ***@***.***>; Author ***@***.***>
Ämne: Re: [Nerwyn/service-call-tile-feature] Selector button icon size (Issue #36)


The icon sizes were reduced to match the Home Assistant built in selectors, they were actually too big before. Set --mdc-icon-size on each selector button.

:host {
  --mdc-icon-size: 32px !important;
}

I'll see if I can rework this style so it can also be set at the entire selector level.

**Comment by Nerwyn** [comment]
As of the latest beta, you can now set the icon size for the entire row using the styles above.
