### ISSUE TITLE
Adding the toggle action 

### ISSUE THREAD

**Issue by MathisP75** [Nerwyn/service-call-tile-feature#42]
**Is your feature request related to a problem? Please describe.**
 The action for a tile card can be "toggle", but the option is missing for a custom button.

**Describe the solution you'd like**
Adding the "toggle" option to custom buttons would be practical.

**Additional context**
For example, I would like to make a button to toggle my Pi-Hole. I cannot do it using this add-on, because the "toggle" option is not available. However, all of the other options are present.

Tile card tap action:
![Screenshot_20240802-082202.png](https://github.com/user-attachments/assets/8a7f320a-3a9d-417a-bd6a-8d64fca2aec7)

Using this add-on:
![Screenshot_20240802-082226.png](https://github.com/user-attachments/assets/1191593d-4364-4de6-86ba-5da55c6378fc)

**Comment by MathisP75** [comment]
I have managed to achieve what I wanted using the "Call Service" action with the "switch: Toggle" service. I guess this is the intended way to do it?

**Comment by Nerwyn** [comment]
The toggle action is a shortcut for calling various toggle services. I never got around to implementing it but I should.

**Comment by Nerwyn** [comment]
I spent a decent amount of time tracking down [the frontend implementation of the toggle action](https://github.com/home-assistant/frontend/blob/d6df228e174017f491df486b89fe248c7ef58751/src/panels/lovelace/common/entity/toggle-entity.ts), but it should be fine to just call the service `homeassistant.toggle`. @MathisP75 can you spot check the 4.0.5 beta to make sure it works fine for you?

**Comment by Nerwyn** [comment]
The generic toggle doesn't work for some domains like locks, so I do have to implemented the rest of the logic 🙃.

**Comment by Nerwyn** [comment]
Alright, beta 2 uses similar logic as the HA frontend to to check entity states and call the appropriate service using that.

**Comment by MathisP75** [comment]
Thank you, it works!

**Comment by Nerwyn** [comment]
Great! I'm gonna work on a few more minor improvements then release it.

**Comment by Nerwyn** [comment]
Released [4.0.5](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/4.0.5).
