### ISSUE TITLE
Conditionally add a tile feature?

### ISSUE THREAD

**Issue by codemunkie15** [Nerwyn/service-call-tile-feature#46]
Hi

Is there any way to conditionally add a tile feature, based on a template?

I'm using an auto-entities card to render some tiles but I only want to add custom tile features on some of the tiles (I only want to add/show the tile feature if the entity has a specific label, if this helps).

Many thanks

**Comment by codemunkie15** [comment]
Some of the examples show the use of `:host { display: none; }` but that adds some extra padding to the card compared to when a tile has no padding:

![image](https://github.com/user-attachments/assets/73f16d11-2f10-4435-b9c6-5170428a3eaa)

Left is with features but `display: none`, right is without features.

**Comment by Nerwyn** [comment]
A recent change in 2024.8 to how card features was laid out added a gap between features (defined in CSS by --feature-padding). Unfortunately this ends up creating two gaps when a custom feature is hidden. There isn’t a good way to fix it with this project as we can only apply styles on the custom feature level and lower. The custom feature is nested within the shadow-root of `hui-card-feature`, which is what is actually in the the card features container flexbox and is causing the gap. Setting `display: none` on this element does remove the gaps, but I'm not sure if there's a good way to apply styles to it outside of dev tools. It may be possible with card-mod.

![image](https://github.com/user-attachments/assets/70edafcb-73f0-43eb-80c4-abe45b4ddf86)

**Comment by codemunkie15** [comment]
As you suggest, using card_mod to set `display: none;` on the `hui-card-features` element does work, but as with all card_mod hacks, the content still appears on a page refresh and then disappears when card_mod kicks in, which is a bit frustrating.

Would it be possible to implement an option on the service-call entries to enable/disable, that accepts a template instead?

Something like:

```
features:
  - type: custom:service-call
    entries:
      - type: button
        enabled: "{{template here that returns true or false}}"
```

Thanks

**Comment by Nerwyn** [comment]
It wouldn't be possible. As I said above we only have control over the custom feature level and lower, which is nested inside the shadow-root of `hui-card-feature`. This would be a feature request for the [Home Assistant frontend repo](https://github.com/home-assistant/frontend/issues).
