### ISSUE TITLE
Add button click/press visual confirmation

### ISSUE THREAD

**Issue by srodighiero** [Nerwyn/service-call-tile-feature#5]
It would be great to have a visual effect of the "tap_action", like for example the temporary icon color (yellow) as a button card when it is executing the command.

Currently there is no visual way to understand if the button as been pressed or not.

**Comment by Nerwyn** [comment]
Do you mean to change it's colors when it's on/off or when you click on it? Currently buttons change opacity (and possibly color for buttons within the selector) when [hovered over or held down](https://github.com/Nerwyn/service-call-tile-feature/blob/main/src/classes/service-call-button.ts#L52-L65) and also have a CSS transition. I want to do a refactor of how CSS styles are set in the future which would make more options available to the user.

You could use card-mod and jinja templates to set a CSS custom attribute and then reference that in the card if you want the slider features to change colors based on entity states. I talked about how to do it [here](https://community.home-assistant.io/t/service-call-tile-features-buttons-sliders-and-selectors/620724/21?u=nerwyn). I would like to eventually add jinja templating support to my projects (and rip out the janky string interpolation system I made for this project) but I haven't figured out how to do so yet.

**Comment by Nerwyn** [comment]
@srodighiero I've added templating in [v3.0.0](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/v3.0.0). Do you think you could use templating to solve your issue? I'm still not sure if you wanted the icon/label/color to change with entity states or something else, but this should allow you to do the former.

**Comment by srodighiero** [comment]
What I meant it's to have anything visual that can confirm you have pressed the button (temporary icon color change, shadow, whatever). Thanks for the update in any case, I'll have a look on templating

**Comment by pathofleastresistor** [comment]
I believe Home Assistant tends to use [Material's Ripple effect](https://m2.material.io/develop/ios/supporting/ripple) to visually indicate a tap action.

**Comment by Nerwyn** [comment]
Implemented in [v3.0.5](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/3.0.5).

**Comment by Nerwyn** [comment]
Given that the custom service call button tap and hold effects now match those of the native Home Assistant tile feature buttons, I'm going to close this card as complete.
