### ISSUE TITLE
Add Custom Feature button not working in Tile Card Configuration for Core 2024.10.0b6

### ISSUE THREAD

**Issue by cloudbr34k84** [Nerwyn/service-call-tile-feature#52]
Description:
The "Add Custom Feature" button in the Tile Card Configuration is currently non-functional, as shown in the attached screenshot. However, you can still add custom features by directly editing the YAML code.
![a3d11d326c4375df4a0625173066f77205df00af_2_690x429](https://github.com/user-attachments/assets/6acfa2ea-6ac6-42d0-a6f9-4509574cc8d4)

**Steps to Reproduce:**
Open the Tile Card Configuration.
Attempt to add a custom feature using the "Add Custom Feature" button.
Observe that the button does not function as expected.

**Expected Behavior:**
The "Add Custom Feature" button should allow users to add a custom feature without requiring manual YAML code editing.

**Actual Behavior:**
The button does not work, and users must switch to YAML editing to add custom features.

**Additional Information:**
Home Assistant Version:2024.10.0b6
Tile Card Version: 4.0.10

**Comment by Nerwyn** [comment]
@cloudbr34k84 can you try again in the 2024.10 release version? I just upgraded and it's still working for me. It may have been an issue with the Home Assistant custom element itself that they fixed.

**Comment by cloudbr34k84** [comment]
> @cloudbr34k84 can you try again in the 2024.10 release version? I just upgraded and it's still working for me. It may have been an issue with the Home Assistant custom element itself that they fixed.
> 
> Edit: nevermind. I can open the drop-down and click on an option but it isn't added to the list.

Pheww!!! sorry if i didnt explain it better

**Comment by Nerwyn** [comment]
For my reference:

https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/editor/config-elements/hui-card-features-editor.ts#L343-L361

https://github.com/home-assistant/frontend/blob/dev/src/components/ha-button-menu.ts

**Comment by Nerwyn** [comment]
@cloudbr34k84 try the [latest 4.0.11 alpha](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/4.0.11-alpha.044)

**Comment by cloudbr34k84** [comment]
> @cloudbr34k84 try the [latest 4.0.11 alpha](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/4.0.11-alpha.044)

i will later, got bigger issues with 2024.10 is starting then rebooting every 10mins or so

**Comment by cloudbr34k84** [comment]
@Nerwyn yep just checked fixed. can now add again. Thanks

**Comment by Nerwyn** [comment]
[Fixed in 4.0.11](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/4.0.11)
