### ISSUE TITLE
Support for dropdown menus

### ISSUE THREAD

**Issue by C4-Dimitri** [Nerwyn/service-call-tile-feature#56]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Not really a problem, but its annoying to have many options in a selector rather than a dropdown menu.

**Describe the solution you'd like**
Custom feature for dropdown menus, very similar to the selector feature where the custom feature allows you to select the options and apply css to each option.
... would even be nice to be able to have an icon for each option...

**Describe alternatives you've considered**
You can use the selector instead of a dropdown, but dropdown is better for options that need text explainers and for more options than looks good with a selector.

**Additional context**
Default dropdown feature:
![SmartSelect_20241019_141036_Home Assistant](https://github.com/user-attachments/assets/9e8bffc4-8c19-4f6e-8b5f-0ffbbfa01f4d)

**Comment by Nerwyn** [comment]
I've been procrastinating on adding this since no one else has requested it yet. It should work like a simpler selector in that it has options but they only support a single action rather than being buttons. I should be able to use a generic [HTML select element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select).

**Comment by Nerwyn** [comment]
Bad news - I can't use the HTML select element for this as it's very limited in what styles it'll select. I'll have to create something more custom to mimic the styles of the default dropdown features.

**Comment by Nerwyn** [comment]
Dropdowns are in beta! Download the latest 4.2.0 beta and give it a try! They should look and behave exactly like the default feature dropdowns. Feedback wanted!

**Comment by C4-Dimitri** [comment]
> Dropdowns are in beta! Download the latest 4.2.0 beta and give it a try! They should look and behave exactly like the default feature dropdowns. Feedback wanted!

Works great! I have had 0 issues so far and they function just like the regular dropdown. Love that icons are supported.

CSS seems super simple to modify too, so 0 complaints from me :)

Great job!

**Comment by Nerwyn** [comment]
Released [4.2.0](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/4.2.0)!
