### ISSUE TITLE
Add variable for the tile entity

### ISSUE THREAD

**Issue by clau-bucur** [Nerwyn/service-call-tile-feature#58]
I'm using YAML exclusively and it's pretty tedious to have to write the same entity for the same feature entry, even though most of them refer to the main entity of the parent tile card.

Taken this code from your examples:
```
- type: tile
  entity: climate.sat
  state_content:
    - state
    - hvac_action
  features:
    - type: custom:service-call
      entries:
        - type: spinbox
          icon: mdi:thermometer
          label: '{{ value }}{{ unit }}'
          step: 1
          debounceTime: 1000
          autofill_entity_id: true
          range:
            - '{{ state_attr("climate.sat", "min_temp") }}'
            - '{{ state_attr("climate.sat", "max_temp") }}'
          value_attribute: temperature
          unit_of_measurement: °C
          hold_action:
            action: repeat
          entity_id: climate.sat
          styles: |-
            :host {
              --background: var(--feature-color);
              --icon-color: var(--feature-color);
              flex-flow: row;
            }
          tap_action:
            action: perform-action
            perform_action: climate.set_temperature
            target:
              entity_id: climate.sat
            data:
              temperature: '{{ value }}'
```
 
It would be nice to replace all the references of `climate.sat` from the features section with a template variable.
Eg.
  `'{{ state_attr("climate.sat", "min_temp") }}'` -> `'{{ state_attr(entity, "min_temp") }}'`
  `'target: entity_id: climate.sat` -> `target: entity_id: '{{ entity }}'`

Thanks for your work!

**Comment by Nerwyn** [comment]
You already can. [Per the README](https://github.com/Nerwyn/service-call-tile-feature?tab=readme-ov-file#a-note-on-templating), use `config.entity` in a template to reference the entity ID of a custom feature, like `{{ state_attr(config.entity, "min_temp") }}`.

**Comment by clau-bucur** [comment]
@Nerwyn indeed, I saw that about `config.entity` but I was actually refering to the **entity ID of the tile card** which would be nice to be accessible all throughout the custom feature.

**Comment by Nerwyn** [comment]
That I can also do. It'll be a bit before I get around to it as I'm working on a minor release for another project.

**Comment by clau-bucur** [comment]
That is great news. Thanks!

**Comment by Nerwyn** [comment]
Added parent card `stateObj` to the template context in [4.1.1](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/4.1.1).

See [this part of the README](https://github.com/Nerwyn/service-call-tile-feature?tab=readme-ov-file#a-note-on-templating) for more information. The `stateObj` contains information about the parent card entity, including it's entity ID, state, and attributes. It can be accessed in a template like `{{ state_attr(stateObj.entity_id, "min_temp") }}` or `{{ stateObj.attributes.min_temp }}`.
