### ISSUE TITLE
Not sure what to make of it?

### ISSUE THREAD

**Issue by cloudbr34k84** [Nerwyn/service-call-tile-feature#59]
Hey @Nerwyn 
i tried re adding the below code to its own dashboard. As soon as its added my browser comes to screeching stop.  have to a do few F5;s in order to be able to just deleted the dashboard.. so i can use HA browser again

im still waiting for new computer, but i find it interesting? Thoughts?
[climate section.txt](https://github.com/user-attachments/files/17631484/climate.section.txt)

**Comment by Nerwyn** [comment]
It loads instantaneously for me.

![image](https://github.com/user-attachments/assets/c5f8cdfa-f54f-4d5b-96f2-965da6c5ceeb)

**Comment by cloudbr34k84** [comment]
Thanks for trying..
Yeah I'll try that.. you can close this down
