### ISSUE TITLE
Purpose of Setting "Update after action delay" in Dropdown

### ISSUE THREAD

**Issue by borgwald74** [Nerwyn/service-call-tile-feature#67]
Hello, i don't understand the mentioned setting "Update after action delay" in Dropdown. As of now, when i select an option in my Dropdown, this setting empties my selection after the given amount of time and leaves a blank field. My understanding is, that the dropdown-field should keep and show the last choosen option. Unfortenatly there is no setting to deactivate "Update after action delay". Setting it to a long amount of time is a workaround, but deactivating it completely would be better. 

Also is there a possibilty to remember the last choosen Option after reloading the Dashboard. Problem is, that every time i change to a different Entry in my Sidebar and change back to my Dashboard the dropdown-field is blank and does not show the current choosen option.

I am using Dropdown with a templated select (not an input_select).

**Comment by Nerwyn** [comment]
`Update after action delay` delays features from retrieving their value from the hass object after you change it manually. This prevents it's value from jumping between it's old and new value as the Home Assistant backend updates the value. It's especially useful for things like thermostats which take a few seconds to update their modes and subsequently their corresponding select entities after you change them.

It sounds like your card is misconfigured, share your config.

**Comment by borgwald74** [comment]
Hello.

This is my simplified Code. It is mostly copied from your example in which you used the dropdown. 

#
features:
  - type: light-brightness
  - type: custom:service-call
    entries:
      - type: dropdown
        entity_id: light.wled
        options:
          - entity_id: light.wled
            option: Solid
            tap_action:
              action: perform-action
              perform_action: light.turn_on
              target:
                entity_id: light.wled
              data:
                effect: Solid
type: tile
entity: light.wled
name: WLED Fensterbank
tap_action:
  action: navigate
  navigation_path: /dashboard-ubersicht/wled-fensterbank
show_entity_picture: false
hide_state: false
vertical: false
color: yellow
icon: mdi:led-strip-variant

**Comment by borgwald74** [comment]
You are right. Missed the value_attribute in my yaml.
