### ISSUE TITLE
Card creation window stays open for first card even if another card is edited

### ISSUE THREAD

**Issue by NewsGuyTor** [Nerwyn/service-call-tile-feature#74]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.22

**Browser and Operating System:**
macOS, all browsers

**Description of problem:**

https://github.com/user-attachments/assets/1797d898-82c0-4ff5-9bd3-c03cafa65647

As you can see, the window for Custom Features for Home Assistant Cards stays open for the card it was opened for even if you switch to editing another card in a stack/grid.

**Comment by Nerwyn** [comment]
Unfortunately, this is an issue with Home Assistant and not this project. You can recreate it with the default features which have configurable options like `climate` entities.

https://github.com/user-attachments/assets/2a5f3c13-78f6-4379-a906-3dc51862ddd2
