### ISSUE TITLE
Add options to Show/Hide titles and icons

### ISSUE THREAD

**Issue by Celzor** [Nerwyn/service-call-tile-feature#8]
Is it possible to add simple boolean options for showing icons and names/labels

eg:
hide_label: true/false
hide_name: true/false
hide_icon: true/false

I understand this can be done with card-mod/CSS, but having toggle options would make the life of this developer a lot easier.

The vision is 
Before:
hide_name: false (default to false)
hide_icon: false (default to false)
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/71630248/488243e5-7d51-4924-bda6-e267eb32f10d)
After:
hide_name: true
hide_icon: true

![image](https://github.com/Nerwyn/service-call-tile-feature/assets/71630248/3c27c8ab-e34c-495a-8b91-7fb7d5b96a42)

**Comment by Nerwyn** [comment]
Modifying the tile icon and labels are out of scope of this project. This project is just for the tile features.

More specifically, this project defines and adds a new tile feature to `window.customTileFeatures` [as described here](https://developers.home-assistant.io/blog/2023/02/28/custom-tile-features/). Modifying anything outside of the custom tile feature is out of scope.
